# Generated by Django 3.1.3 on 2020-12-25 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('title', models.CharField(max_length=225)),
                ('body', models.CharField(max_length=225)),
                ('done', models.BooleanField(default=False)),
                ('pause', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
    ]
